### ISSUE TITLE
玩家中途退出游戏, 重新加入后, 上一句的出牌未清除

### ISSUE THREAD

**Issue by tokinonagare** [kevinanew/laiwan_react_native#164]
![image](https://user-images.githubusercontent.com/6461520/41805201-baa6cb86-76d7-11e8-978b-6d76502e2a95.png)
这里的 4 个 "9" 是在 Thanos 退出前出的牌, 在 Thanos 返回游戏, 重新发牌后, 这 4 个 "9" 还在场地上

**Comment by markrookie** [comment]
服务端，返回的状态错了，有人退出后也是playing_card状态，并且有这些牌，后端修复了。
