### ISSUE TITLE
Android bug 修复

### ISSUE THREAD

**Issue by tokinonagare** [kevinanew/laiwan_react_native#285]
- [x] 点击 "加入来玩" crash;
- [x] 头像 等 页面 自定义 返回 & 确认 等标签无法出现;
- [x] Input text 有两条下划线 & 输入电话显示不全;
- [x] 昵称 & 个性签名 输入文字后, 无法正常显示
- [x] 点击 通讯录 tabBar 会卡顿(猜测是网络请求导致的阻塞);
- [x] 启动需要添加图片(现在是白屏);
- [x] 通讯录中的返回按钮很难按;
- [x] 登录 & 注册界面, 按钮不会跟随键盘移动(遮挡 input 区域);
- [x] 注册时, 日期无法选择
- [x] 无法更新头像;
- [x] 搜索好友处的输入框下划线
- [x] 聊天 输入文字后, 无法正常显示;
- [x] 注册 username 输入界面 crash;
- [ ] ~~任务栏中的 icon 没有更改(Notification 中的 icon);~~

**Comment by tokinonagare** [comment]
> https://github.com/FaridSafi/react-native-gifted-chat/issues/937

针对 "聊天 输入文字后, 无法正常显示" 发出 issue 求助

**Comment by tokinonagare** [comment]
> https://github.com/FaridSafi/react-native-gifted-chat/issues/137
https://github.com/facebook/react-native/issues/18403
https://github.com/facebook/react-native/issues/19339
https://github.com/facebook/react-native/issues/18874

由于, react native 的 bug, stan 做了自定义, 所以在 android 中出现问题

聊天 输入文字, 无法显示

**Comment by tokinonagare** [comment]
点击 通讯录 tabBar 会卡顿(猜测是网络请求导致的阻塞)

目前在 1 + 5 上没有该问题, 暂时不处理

**Comment by ycai2** [comment]
插个嘴 facebook/react-native#18874 是一个iOS issue

**Comment by ycai2** [comment]
@tokinonagare 哦哦, 不好意思...希望RN早点修好吧...

**Comment by tokinonagare** [comment]
@ycai2 是啊...3个版本都没修了... 0.57 快出了, 希望能修掉 : )

**Comment by ycai2** [comment]
@tokinonagare 兄弟帮帮忙, 上 https://github.com/facebook/react-native/issues/18874 帮忙一起催一下, 点两个赞...我公司的app都修不了只能倒回53

**Comment by tokinonagare** [comment]
> Android: It works only on release builds, don't worry if it shows nothing on DEBUG builds

关于 android 头像在 debug 模式下, defaultSource 不会显示 (release 是没问题的)

**Comment by tokinonagare** [comment]
@ycai2 我们准备用改原生的方法来处理, 打包的时候打一个 patch 到原生的文件上

**Comment by tokinonagare** [comment]
暂时完成该 issue, 关闭
